/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      "colors": {
        "on-surface": "#191c1e",
        "surface-container-low": "#f2f4f6",
        "tertiary-fixed-dim": "#ffb596",
        "surface": "#f7f9fb",
        "on-error": "#ffffff",
        "outline": "#74777f",
        "on-primary-container": "#6f84ae",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#360f00",
        "secondary-container": "#68fade",
        "tertiary": "#000000",
        "surface-container-highest": "#e0e3e5",
        "secondary-fixed": "#68fade",
        "primary-fixed": "#d7e2ff",
        "error": "#ba1a1a",
        "on-tertiary-container": "#b37459",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#ffdbcd",
        "primary": "#000000",
        "on-background": "#191c1e",
        "primary-container": "#001a3f",
        "on-error-container": "#93000a",
        "background": "#f7f9fb",
        "surface-tint": "#4a5e87",
        "primary-fixed-dim": "#b2c7f5",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#001a3f",
        "on-tertiary-fixed": "#360f00",
        "on-secondary-fixed-variant": "#005045",
        "outline-variant": "#c4c6cf",
        "surface-variant": "#e0e3e5",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#32476d",
        "on-tertiary-fixed-variant": "#6c3922",
        "on-secondary-fixed": "#00201b",
        "secondary": "#006b5c",
        "surface-dim": "#d8dadc",
        "secondary-fixed-dim": "#44ddc2",
        "surface-container-high": "#e6e8ea",
        "surface-bright": "#f7f9fb",
        "inverse-primary": "#b2c7f5",
        "inverse-on-surface": "#eff1f3",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#007162",
        "surface-container": "#eceef0",
        "on-surface-variant": "#44474e",
        "inverse-surface": "#2d3133"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "sidebar_width": "280px",
        "container_max_width": "1440px",
        "stack_lg": "32px",
        "margin_desktop": "40px",
        "gutter": "24px",
        "margin_mobile": "16px",
        "stack_md": "16px",
        "stack_sm": "8px"
      },
      "fontFamily": {
        "label-sm": ["Inter"],
        "label-md": ["Inter"],
        "display-lg": ["Outfit"],
        "headline-lg": ["Outfit"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-md": ["Outfit"],
        "headline-sm": ["Outfit"],
        "headline-lg-mobile": ["Outfit"]
      },
      "fontSize": {
        "label-sm": ["12px", {"lineHeight": "1.2", "letterSpacing": "0.08em", "fontWeight": "600"}],
        "label-md": ["14px", {"lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "letterSpacing": "0", "fontWeight": "500"}],
        "headline-sm": ["20px", {"lineHeight": "1.4", "letterSpacing": "0.01em", "fontWeight": "500"}],
        "headline-lg-mobile": ["28px", {"lineHeight": "1.2", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
};
